- name: Demonstratates use of git_config ansible module
  hosts: localhost
  tasks:
   - name: Print Git all config details of TekTutor GitHub Repo of this training
     git_config:
       list_all: yes
       repo: https://github.com/tektutor/ansible-1425June-2021.git
     register: output

   - debug: var=output

   - name: Set Git config user.email
     git_config:
       name: user.email
       value: "someemail@gmail.com"
       state: present
       scope: local
       repo: .
     register: output

   - debug: var=output

   - name: Set Git config user.name
     git_config:
       name: user.name
       value: "Michael Deehan"
       state: present
       scope: local
       repo: .
     register: output

   - debug: var=output
