- name: Demonstrates building docker image via Ansible playbook
  hosts: localhost
  vars:
    delete_images: yes 

  tasks:
     - name: Check if ubuntu or centos containers are running
       shell: docker ps -aq --filter "name=docker-jenkins-slave*" | wc -w
       register: output 
       tags:
         - debug

     - debug: var=output
       tags:
         - debug

     - name: Dispose containers with name patterns ubuntu*
       shell: docker rm -f $(docker ps -aq --filter "name=docker-jenkins-slave*")
       when: ( delete_images == "yes" and output.stdout != "0")
       tags:
         - debug

     - name: Cleanup the existing tektutor images
       shell: docker rmi -f tektutor/jenkins-node-ubuntu:latest
       ignore_errors: yes
       tags:
         - debug

     - name: Build ubuntu docker images
       docker_image:
           docker_host: tcp://localhost:4243
           name: "tektutor/jenkins-node-ubuntu:latest"
           state: present 
           source: build  
           build:
             dockerfile: UbuntuDockerfile
             path: .
             pull: yes
